services:
  - type: web
    name: photoid-backend
    env: python
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
    # Monorepo ayarları
    rootDir: backend 